#! /bin/bash
# /usr/local/sbin/aide_update

DB_DIR=/var/lib/aide
DB_FILE=${DB_DIR}/aide.db.gz
NEW_DB_FILE=${DB_DIR}/aide.db.new.gz

if [ -f $NEW_DB_FILE ]; then
	mv ${DB_FILE} ${DB_FILE}.1
	mv ${NEW_DB_FILE} ${DB_FILE}
else
	echo "Nothing to update"
fi
